export enum WHATSAPP_MESSAGE_CONTENT_TYPE {
  TEXT = 'TEXT',
  AUDIO = 'AUDIO',
  CONTACT = 'CONTACT',
  DOCUMENT = 'DOCUMENT',
  IMAGE = 'IMAGE',
  LINK = 'LINK',
  LOCATION = 'LOCATION',
  STICKER = 'STICKER',
  VIDEO = 'VIDEO',
}
