export enum WHATSAPP_CLIENT_STATUS {
  NONE = 'NONE',
  BUILDING = 'BUILDING',
  ACTIVE = 'ACTIVE',
  ERROR = 'ERROR',
  FAILED = 'FAILED',
  STOPPED = 'STOPPED',
  LOGGEDOUT = 'LOGGEDOUT',
  NEEDQR = 'NEEDQR',
}
